apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicy-deployment
  labels:
    app: juicy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juicy
  template:
    metadata:
      labels:
        app: juicy
    spec:
      containers:
      - name: juicy
        image: mywebserver:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juicy-service
spec:
  selector:
    app: juicy
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer