name: Build and Deploy Docker image

on:
  push:
    branches:
    - master

env:
  AWS_REGION: us-east-1

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: |
        npm install --production --unsafe-perm
    - uses: sburris/dependency-check-action@master
      with:
        Project-Name: JuiceShop
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: blyseur/juicy
        tag_with_sha: true
    - name: prepare-kustomize
      run: |
        sed -i "s#IMAGE_NAME#blyseur/juicy#g" kustomization.yaml
        sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
        cat kustomization.yaml
    - name: configure-aws
      run: |
        aws configure set default.region $AWS_REGION
        aws configure set default.output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
    - name: deploy-to-k8s
      run: |
        aws eks update-kubeconfig --name isen
        kubectl kustomize . | kubectl apply -f -